# NORMALIZATION PROBLEM

In [35]:
import numpy as np

#Create a random 5x5 ndarray, storing it into X and then display
X = np.random.rand(5,5)
print("Random 5x5 ndarray: ")
print(X)

#Calculating the mean and sd of x
mean_of_X = X.mean()
std_of_X = X.std()

#Normalizing x using the given formula and displaying the result
X_normalized = (X - mean_of_X) / std_of_X
print("\nNormalized X: ")
print(X_normalized)

#Save the normalized ndarray 
np.save('X_normalized.npy', X_normalized)




Random 5x5 ndarray: 
[[0.3439769  0.02735126 0.55577407 0.37393299 0.17624033]
 [0.18354531 0.12026152 0.83535547 0.25012341 0.53747113]
 [0.41921964 0.19596103 0.53366411 0.72127142 0.62167004]
 [0.06376529 0.01232753 0.38486803 0.26190707 0.99075511]
 [0.18336614 0.22435123 0.75940533 0.12263346 0.075794  ]]

Normalized X: 
[[-0.05655745 -1.2485834   0.74081237  0.05622064 -0.68804876]
 [-0.66054712 -0.89879669  1.79337491 -0.40989522  0.67190582]
 [ 0.22671496 -0.61380467  0.65757323  1.36387352  0.98889623]
 [-1.1114926  -1.30514444  0.0973887  -0.36553232  2.37842043]
 [-0.66122168 -0.50692181  1.50743931 -0.88986684 -1.06620712]]


# DIVISIBLE BY 3 PROBLEM

In [33]:
import numpy as np

def ndarray_and_div_by_3():
    # Create a 10x10 ndarray of the first 100 integers, by squaring it and arranging into a 10x10 ndarray
    A = np.square(np.arange(1,101).reshape(10,10))
    print("A = ")
    print(A)

    #Finding elements in ndarray A that is divisible by 3
    div_by_3 = A[A % 3 == 0]
    print("\nElements divisible by 3: ")
    print(div_by_3)
    
    #Save the result of the elements that are divisble by 3 as div_by_3.npy
    np.save('div_by_3.npy',div_by_3)

ndarray_and_div_by_3()

A = 
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3: 
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
